modLoader = "javafml"
loaderVersion = "[2,)"
issueTrackerURL = "https://github.com/RX0kas/entity-purge/issues/"
license = "MIT"

[[mods]]
modId = "entitypurge"
version = "${version}"
displayName = "EntityPurge"
authors = "RXokas"
description = '''
A simple ClearLag mod that aims to be as customizable as possible
'''
logoFile = "logo.png"

[[dependencies.entitypurge]]
modId = "neoforge"
type = "required"
versionRange = "[21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.entitypurge]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.4,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.entitypurge]]
modId = "architectury"
type = "required"
versionRange = "[15.0.1,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.entitypurge]]
modId = "midnightlib"
type = "required"
versionRange = "[1.6.7,)"
ordering = "BEFORE"
side = "BOTH"